# Generated by Django 3.0.3 on 2021-12-18 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContraEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('particular', models.CharField(max_length=50)),
                ('debit', models.IntegerField(blank=True, null=True)),
                ('credit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('particular', models.CharField(max_length=50)),
                ('debit', models.IntegerField(blank=True, null=True)),
                ('credit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('dep', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('particular', models.CharField(max_length=50)),
                ('debit', models.IntegerField(blank=True, null=True)),
                ('credit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('particular', models.CharField(max_length=50)),
                ('debit', models.IntegerField(blank=True, null=True)),
                ('credit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250, null=True)),
                ('rate', models.FloatField()),
                ('Qty', models.FloatField()),
                ('Discount', models.FloatField()),
                ('Tax', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PO_Number', models.CharField(max_length=50)),
                ('PO_Date', models.DateField()),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('Qty', models.FloatField(blank=True, null=True)),
                ('Discount', models.FloatField(blank=True, null=True)),
                ('Tax', models.FloatField(blank=True, null=True)),
                ('Total', models.FloatField(blank=True, null=True)),
                ('Vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Company')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
            options={
                'verbose_name_plural': 'purchaseOrder',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice_number', models.CharField(max_length=30)),
                ('Invoice_date', models.DateField()),
                ('payment_terms', models.CharField(choices=[('STRIPE', 'stripe'), ('WORLDPAY', 'worldpay'), ('CHEQUE', 'cheque'), ('BANK_TRANSFER', 'bank_transfer'), ('CASH', 'cash')], max_length=100)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('rate', models.FloatField(blank=True, default=0, null=True)),
                ('Qty', models.FloatField(blank=True, default=0, null=True)),
                ('Discount', models.FloatField(blank=True, default=0, null=True)),
                ('Tax', models.FloatField(blank=True, default=0, null=True)),
                ('Total', models.FloatField(blank=True, null=True)),
                ('client_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'invoice',
            },
        ),
    ]
