# Generated by Django 3.0.3 on 2021-12-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='Total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
