# Generated by Django 3.0.3 on 2021-12-19 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customernew_vendornew'),
        ('finance', '0002_auto_20211219_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.CustomerNew'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='Vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.VendorNew'),
        ),
    ]
