# Generated by Django 3.0.3 on 2021-12-24 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20211221_1655'),
        ('finance', '0003_auto_20211219_1814'),
    ]

    operations = [
    ]
