# Generated by Django 3.0.3 on 2022-01-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20220107_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionmaterial',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
