# Generated by Django 3.0.3 on 2021-12-18 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptId', models.CharField(max_length=10)),
                ('dept_name', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'department',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_holidays_allowed', models.IntegerField()),
                ('salary_package', models.IntegerField()),
                ('Joining_date', models.DateField(null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('isactive', models.BooleanField(default=False)),
                ('EmpId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.EmployeeProfile')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.Department')),
                ('packageId', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeePackage')),
            ],
            options={
                'verbose_name_plural': 'staffProfile',
            },
        ),
    ]
