# Generated by Django 3.0.3 on 2021-12-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
