# Generated by Django 3.0.3 on 2021-12-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20211219_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Tax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='quantity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
