# Generated by Django 3.0.3 on 2021-12-18 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(blank='False', max_length=100, null='False')),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('LOW', 'Low'), ('MODERATE', 'Moderate')], default='', max_length=200)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('IN PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], max_length=200, null=True)),
                ('solution_details', models.CharField(max_length=200, null='True')),
                ('customer_name', models.ManyToManyField(to='authentication.Customer')),
                ('responsible_person', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='authentication.EmployeeProfile')),
            ],
            options={
                'verbose_name_plural': 'SLA',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField(blank=True, max_length=300)),
                ('ticket_no', models.CharField(blank=True, max_length=300)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Customer')),
            ],
            options={
                'verbose_name_plural': 'History',
            },
        ),
    ]
