# Generated by Django 3.0.3 on 2021-12-18 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('firstname', models.CharField(max_length=50)),
                ('company_create_permission', models.BooleanField(blank=True, null=True)),
                ('company_read_permission', models.BooleanField(blank=True, null=True)),
                ('company_edit_permission', models.BooleanField(blank=True, null=True)),
                ('company_delete_permission', models.BooleanField(blank=True, null=True)),
                ('contactperson_create_permission', models.BooleanField(blank=True, null=True)),
                ('contactperson_read_permission', models.BooleanField(blank=True, null=True)),
                ('contactperson_edit_permission', models.BooleanField(blank=True, null=True)),
                ('contactperson_delete_permission', models.BooleanField(blank=True, null=True)),
                ('project_create_permission', models.BooleanField(blank=True, null=True)),
                ('project_read_permission', models.BooleanField(blank=True, null=True)),
                ('project_edit_permission', models.BooleanField(blank=True, null=True)),
                ('project_delete_permission', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150, null=True)),
                ('business_owner', models.CharField(max_length=150)),
                ('business_address', models.CharField(max_length=150, null=True)),
                ('street', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=150, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.CharField(max_length=150, null=True)),
                ('business_phone', models.CharField(max_length=150, null=True)),
                ('business_emailId', models.CharField(blank=True, max_length=150, null=True)),
                ('business_website', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_Name', models.CharField(max_length=150, null=True)),
                ('company_Address', models.CharField(max_length=150, null=True)),
                ('street', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=150, null=True)),
                ('zip_code', models.CharField(max_length=150, null=True)),
                ('country', models.CharField(max_length=150, null=True)),
                ('company_Phone', models.CharField(max_length=150, null=True)),
                ('company_EmailId', models.CharField(max_length=150, null=True)),
                ('company_website', models.CharField(max_length=30)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Business')),
            ],
            options={
                'verbose_name_plural': 'company',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('email_id', models.CharField(max_length=150, null=True)),
                ('govt_id', models.CharField(choices=[('driving license', 'DRIVING LICENSE'), ('passport', 'PASSPORT'), ('aadhar', 'AADHAR CARD'), ('other', 'OTHER')], max_length=150, null=True)),
                ('id_no', models.CharField(max_length=150, null=True, unique=True, verbose_name='')),
                ('p_id1', models.CharField(max_length=150, null=True, verbose_name='PersonalID')),
                ('p_id_link', models.CharField(max_length=500, null=True, unique=True, verbose_name='')),
                ('contact', models.CharField(max_length=20, null=True, verbose_name='PhoneNo.')),
                ('address_1', models.CharField(max_length=150, null=True)),
                ('address_2', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=150, null=True)),
                ('state', models.CharField(max_length=150, null=True)),
                ('country', models.CharField(max_length=150, null=True)),
                ('zip_code', models.CharField(max_length=150, null=True)),
                ('company_Name', models.CharField(max_length=150, null=True)),
                ('company_Address1', models.CharField(max_length=150, null=True)),
                ('company_Address2', models.CharField(max_length=150, null=True)),
                ('company_Phone', models.CharField(max_length=150, null=True)),
                ('company_EmailId', models.CharField(max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'vendor',
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('email_id', models.EmailField(max_length=150, null=True)),
                ('dob', models.DateField()),
                ('contact', models.CharField(max_length=20, null=True, verbose_name='PhoneNo.')),
                ('address_1', models.CharField(max_length=150, null=True)),
                ('address_2', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=150, null=True)),
                ('state', models.CharField(max_length=150, null=True)),
                ('country', models.CharField(max_length=150, null=True)),
                ('zip_code', models.CharField(max_length=150, null=True)),
                ('govt_id', models.CharField(choices=[('driving license', 'DRIVING LICENSE'), ('passport', 'PASSPORT'), ('aadhar', 'AADHAR CARD'), ('other', 'OTHER')], max_length=150, null=True)),
                ('id_no', models.CharField(max_length=150, null=True, unique=True, verbose_name='')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('p_id1', models.CharField(max_length=150, null=True, verbose_name='PersonalID')),
                ('p_id2', models.CharField(max_length=500, null=True, unique=True, verbose_name='')),
                ('upload_documents', models.FileField(blank=True, null=True, upload_to='')),
                ('company_code', models.CharField(max_length=150, null=True)),
                ('position', models.CharField(max_length=150, null=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('hr', models.BooleanField(default=False)),
                ('manager', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('email_id', models.CharField(max_length=150, null=True)),
                ('govt_id', models.CharField(choices=[('driving license', 'DRIVING LICENSE'), ('passport', 'PASSPORT'), ('aadhar', 'AADHAR CARD'), ('other', 'OTHER')], max_length=150, null=True)),
                ('id_no', models.CharField(max_length=150, null=True, unique=True, verbose_name='')),
                ('p_id1', models.CharField(max_length=150, null=True, verbose_name='PersonalID')),
                ('p_id_link', models.CharField(max_length=500, null=True, unique=True, verbose_name='')),
                ('contact', models.CharField(max_length=20, null=True, verbose_name='PhoneNo.')),
                ('address_1', models.CharField(max_length=150, null=True)),
                ('address_2', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=150, null=True)),
                ('state', models.CharField(max_length=150, null=True)),
                ('country', models.CharField(max_length=150, null=True)),
                ('zip_code', models.CharField(max_length=150, null=True)),
                ('company_code', models.CharField(max_length=150, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=150, null=True)),
                ('createdBy', models.ForeignKey(default='', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.EmployeeProfile')),
            ],
            options={
                'verbose_name_plural': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('telephoneNo', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=40)),
                ('wattsapp', models.CharField(blank=True, max_length=40, null=True)),
                ('skype', models.CharField(blank=True, max_length=40, null=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Company')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Position'),
        ),
    ]
